---@meta
-- Auto-generated by PhoenixLuaGen — do not edit.
-- Provides LuaLS type annotations for the Phoenix host API.
-- Regenerate: build the PhoenixLuaGen target.

Phoenix = {}
Phoenix.Orders = {}
Phoenix.Physics = {}
Phoenix.RTS = {}
Phoenix.RTS.AttackAbilityTask = {}
Phoenix.RTS.MoveAbilityTask = {}
Phoenix.RTS.ProjectileTask = {}
Phoenix.RTS.VitalsTask = {}
Phoenix.Random = {}
Phoenix.Steering = {}
Phoenix.Vitals = {}
Phoenix.World = {}

---@class Phoenix.Color
---@field B integer
---@field R integer
---@field G integer
---@field A integer
Phoenix.Color = {}

---@param t? {B?: integer, R?: integer, G?: integer, A?: integer}
---@return Phoenix.Color
function Phoenix.Color.new(t) end

---@param arg0 integer
---@return Phoenix.Color
function Phoenix.Color.FromHex(arg0) end

---@class Phoenix.ECS
---@field bDebugDrawMortonCodeBoundaries boolean
---@field bDebugDrawEntityZCodes boolean
Phoenix.ECS = {}

---@param t? {bDebugDrawMortonCodeBoundaries?: boolean, bDebugDrawEntityZCodes?: boolean}
---@return Phoenix.ECS
function Phoenix.ECS.new(t) end

---@param entity integer
---@param tag integer|string
---@return boolean
function Phoenix.ECS.AddTag(entity, tag) end

---@param kind integer|string
---@return integer
function Phoenix.ECS.AcquireEntity(kind) end

---@param entity integer
---@return integer
function Phoenix.ECS.RemoveAllTags(entity) end

---@param group integer
---@param entity integer
---@return boolean
function Phoenix.ECS.AddEntityToGroup(group, entity) end

---@param entity integer
---@return boolean
function Phoenix.ECS.ReleaseEntity(entity) end

---@param entity integer
---@param kind integer|string
---@return boolean
function Phoenix.ECS.SetEntityKind(entity, kind) end

---@param entity integer
---@param tag integer|string
---@return boolean
function Phoenix.ECS.HasTag(entity, tag) end

---@param entity integer
---@param tag integer|string
---@return boolean
function Phoenix.ECS.RemoveTag(entity, tag) end

---@param group integer
---@param entity integer
---@return boolean
function Phoenix.ECS.GroupContainsEntity(group, entity) end

---@param group integer
---@param entity integer
---@return boolean
function Phoenix.ECS.RemoveEntityFromGroup(group, entity) end

---@param entity integer
---@param target integer
---@param range number
---@return boolean
function Phoenix.ECS.IsInRangeOfEntity(entity, target, range) end

---@param id integer
---@param key integer|string
---@param bool boolean
---@return boolean
function Phoenix.ECS.RemoveBlackboardValue(id, key, bool) end

---@param entity integer
---@return integer
function Phoenix.ECS.RemoveEntityFromAllGroups(entity) end

---@param group integer
---@return integer
function Phoenix.ECS.ClearGroup(group) end

---@param entity integer
---@param target Phoenix.Vec2
---@param threshold number
---@return boolean
function Phoenix.ECS.IsFacingPos(entity, target, threshold) end

---@param group integer
---@return integer
function Phoenix.ECS.GetGroupSize(group) end

---@param id integer
---@param key integer|string
---@param type integer
---@return boolean
function Phoenix.ECS.HasBlackboardValue(id, key, type) end

---@param id integer
---@param key integer|string
---@param type integer
---@return integer
function Phoenix.ECS.CreateBlackboardKey(id, key, type) end

---@param id integer
---@param key integer|string
---@param value number
---@return boolean
function Phoenix.ECS.SetBlackboardValue(id, key, value) end

---@param id integer
---@param key integer|string
---@param defaultValue number
---@return number
function Phoenix.ECS.GetBlackboardValue(id, key, defaultValue) end

---@param entity integer
---@return Phoenix.Vec2
function Phoenix.ECS.GetLocalPosition(entity) end

---@param entity integer
---@param target integer
---@param threshold number
---@return boolean
function Phoenix.ECS.IsFacingEntity(entity, target, threshold) end

---@param entity integer
---@return number
function Phoenix.ECS.GetLocalFacing(entity) end

---@param entity integer
---@param target Phoenix.Vec2
---@param range number
---@return boolean
function Phoenix.ECS.IsInRangeOfPos(entity, target, range) end

---@param entity integer
---@return number
function Phoenix.ECS.GetLocalScale(entity) end

---@param entity integer
---@return Phoenix.Vec2
function Phoenix.ECS.GetWorldPosition(entity) end

---@param entity integer
---@return number
function Phoenix.ECS.GetWorldFacing(entity) end

---@param entity integer
---@return number
function Phoenix.ECS.GetWorldScale(entity) end

---@param entity integer
---@return integer
function Phoenix.ECS.GetParent(entity) end

---@class Phoenix.ECS.TransformComponent
---@field ZCode integer
---@field AttachParent integer
---@field Transform Phoenix.Transform2D
Phoenix.ECS.TransformComponent = {}

---@param t? {ZCode?: integer, AttachParent?: integer, Transform?: Phoenix.Transform2D}
---@return Phoenix.ECS.TransformComponent
function Phoenix.ECS.TransformComponent.new(t) end

---@class Phoenix.Physics.BodyComponent
---@field Force Phoenix.Vec2
---@field Flags integer
---@field Radius number
---@field LinearVelocity Phoenix.Vec2
---@field CollisionMask integer
---@field Movement integer
---@field MaxLinearVelocity number
---@field LinearDamping number
---@field InvMass integer
---@field SleepTimer integer
---@field PreviousPos Phoenix.Vec2
Phoenix.Physics.BodyComponent = {}

---@param t? {Force?: Phoenix.Vec2, Flags?: integer, Radius?: number, LinearVelocity?: Phoenix.Vec2, CollisionMask?: integer, Movement?: integer, MaxLinearVelocity?: number, LinearDamping?: number, InvMass?: integer, SleepTimer?: integer, PreviousPos?: Phoenix.Vec2}
---@return Phoenix.Physics.BodyComponent
function Phoenix.Physics.BodyComponent.new(t) end

---@class Phoenix.Physics.FeaturePhysicsScratchBlock
---@field SortedEntities any
---@field Contacts any
---@field ContactPairs any
---@field ContactPairSet any
---@field ContactFreeHead integer
---@field CollisionLines any
Phoenix.Physics.FeaturePhysicsScratchBlock = {}

---@param t? {SortedEntities?: any, Contacts?: any, ContactPairs?: any, ContactPairSet?: any, ContactFreeHead?: integer, CollisionLines?: any}
---@return Phoenix.Physics.FeaturePhysicsScratchBlock
function Phoenix.Physics.FeaturePhysicsScratchBlock.new(t) end

---@class Phoenix.RTS.Command
---@field Flags integer
---@field Sender integer
---@field TargetEntity integer
---@field Kind integer
---@field TargetLocation Phoenix.Vec2
---@field CommandId integer|string
---@field CommandIndex integer
Phoenix.RTS.Command = {}

---@param t? {Flags?: integer, Sender?: integer, TargetEntity?: integer, Kind?: integer, TargetLocation?: Phoenix.Vec2, CommandId?: integer|string, CommandIndex?: integer}
---@return Phoenix.RTS.Command
function Phoenix.RTS.Command.new(t) end

---@class Phoenix.RTS.Damage
---@field Amount number
---@field ArmorMultiplier number
---@field VitalId integer|string
---@field BaseAmount number
---@field SourceId integer
Phoenix.RTS.Damage = {}

---@param t? {Amount?: number, ArmorMultiplier?: number, VitalId?: integer|string, BaseAmount?: number, SourceId?: integer}
---@return Phoenix.RTS.Damage
function Phoenix.RTS.Damage.new(t) end

---@class Phoenix.RTS.EffectComponent
---@field Name integer|string
---@field TargetId integer
---@field SourceId integer
---@field TargetPos Phoenix.Vec2
---@field SourcePos Phoenix.Vec2
---@field RefCount integer
---@field ChannelingCount integer
Phoenix.RTS.EffectComponent = {}

---@param t? {Name?: integer|string, TargetId?: integer, SourceId?: integer, TargetPos?: Phoenix.Vec2, SourcePos?: Phoenix.Vec2, RefCount?: integer, ChannelingCount?: integer}
---@return Phoenix.RTS.EffectComponent
function Phoenix.RTS.EffectComponent.new(t) end

---@class Phoenix.RTS.UnitComponent
---@field OwningPlayer integer
---@field UnitData integer|string
Phoenix.RTS.UnitComponent = {}

---@param t? {OwningPlayer?: integer, UnitData?: integer|string}
---@return Phoenix.RTS.UnitComponent
function Phoenix.RTS.UnitComponent.new(t) end

---@class Phoenix.ScriptOptional_Angle
---@field HasValue integer
---@field Value number
Phoenix.ScriptOptional_Angle = {}

---@param t? {HasValue?: integer, Value?: number}
---@return Phoenix.ScriptOptional_Angle
function Phoenix.ScriptOptional_Angle.new(t) end

---@class Phoenix.ScriptOptional_Color
---@field HasValue integer
---@field Value Phoenix.Color
Phoenix.ScriptOptional_Color = {}

---@param t? {HasValue?: integer, Value?: Phoenix.Color}
---@return Phoenix.ScriptOptional_Color
function Phoenix.ScriptOptional_Color.new(t) end

---@class Phoenix.ScriptOptional_EntityId
---@field HasValue integer
---@field Value integer
Phoenix.ScriptOptional_EntityId = {}

---@param t? {HasValue?: integer, Value?: integer}
---@return Phoenix.ScriptOptional_EntityId
function Phoenix.ScriptOptional_EntityId.new(t) end

---@class Phoenix.ScriptOptional_FName
---@field HasValue integer
---@field Value integer|string
Phoenix.ScriptOptional_FName = {}

---@param t? {HasValue?: integer, Value?: integer|string}
---@return Phoenix.ScriptOptional_FName
function Phoenix.ScriptOptional_FName.new(t) end

---@class Phoenix.ScriptOptional_Speed
---@field HasValue integer
---@field Value number
Phoenix.ScriptOptional_Speed = {}

---@param t? {HasValue?: integer, Value?: number}
---@return Phoenix.ScriptOptional_Speed
function Phoenix.ScriptOptional_Speed.new(t) end

---@class Phoenix.ScriptOptional_Time
---@field HasValue integer
---@field Value number
Phoenix.ScriptOptional_Time = {}

---@param t? {HasValue?: integer, Value?: number}
---@return Phoenix.ScriptOptional_Time
function Phoenix.ScriptOptional_Time.new(t) end

---@class Phoenix.ScriptOptional_Value
---@field HasValue integer
---@field Value number
Phoenix.ScriptOptional_Value = {}

---@param t? {HasValue?: integer, Value?: number}
---@return Phoenix.ScriptOptional_Value
function Phoenix.ScriptOptional_Value.new(t) end

---@class Phoenix.ScriptOptional_Vec2
---@field HasValue integer
---@field Value Phoenix.Vec2
Phoenix.ScriptOptional_Vec2 = {}

---@param t? {HasValue?: integer, Value?: Phoenix.Vec2}
---@return Phoenix.ScriptOptional_Vec2
function Phoenix.ScriptOptional_Vec2.new(t) end

---@class Phoenix.ScriptOptional_bool
---@field HasValue integer
---@field Value boolean
Phoenix.ScriptOptional_bool = {}

---@param t? {HasValue?: integer, Value?: boolean}
---@return Phoenix.ScriptOptional_bool
function Phoenix.ScriptOptional_bool.new(t) end

---@class Phoenix.ScriptOptional_int
---@field HasValue integer
---@field Value integer
Phoenix.ScriptOptional_int = {}

---@param t? {HasValue?: integer, Value?: integer}
---@return Phoenix.ScriptOptional_int
function Phoenix.ScriptOptional_int.new(t) end

---@class Phoenix.ScriptOptional_int64
---@field HasValue integer
---@field Value integer
Phoenix.ScriptOptional_int64 = {}

---@param t? {HasValue?: integer, Value?: integer}
---@return Phoenix.ScriptOptional_int64
function Phoenix.ScriptOptional_int64.new(t) end

---@class Phoenix.ScriptOptional_uint64
---@field HasValue integer
---@field Value integer
Phoenix.ScriptOptional_uint64 = {}

---@param t? {HasValue?: integer, Value?: integer}
---@return Phoenix.ScriptOptional_uint64
function Phoenix.ScriptOptional_uint64.new(t) end

---@class Phoenix.ScriptOptional_unsigned_int
---@field HasValue integer
---@field Value integer
Phoenix.ScriptOptional_unsigned_int = {}

---@param t? {HasValue?: integer, Value?: integer}
---@return Phoenix.ScriptOptional_unsigned_int
function Phoenix.ScriptOptional_unsigned_int.new(t) end

---@class Phoenix.Steering.SteeringComponent
---@field PreviousPos Phoenix.Vec2
---@field Velocity Phoenix.Vec2
---@field Mode integer
---@field GoalPos Phoenix.Vec2
---@field Flags integer
---@field CollisionMask integer
---@field GoalEntity integer
---@field Slack number
---@field BestPos Phoenix.Vec2
---@field InnerRadius number
---@field OuterRadius number
---@field ArrivalRange number
---@field MaxSpeed number
---@field TurnRateIdle number
---@field TurnRateMoving number
---@field AccelerationTime number
---@field DecelerationTime number
---@field AvoidanceRadius number
---@field SeparationDelay number
---@field SeparationRadius number
---@field SeparationStrength number
Phoenix.Steering.SteeringComponent = {}

---@param t? {PreviousPos?: Phoenix.Vec2, Velocity?: Phoenix.Vec2, Mode?: integer, GoalPos?: Phoenix.Vec2, Flags?: integer, CollisionMask?: integer, GoalEntity?: integer, Slack?: number, BestPos?: Phoenix.Vec2, InnerRadius?: number, OuterRadius?: number, ArrivalRange?: number, MaxSpeed?: number, TurnRateIdle?: number, TurnRateMoving?: number, AccelerationTime?: number, DecelerationTime?: number, AvoidanceRadius?: number, SeparationDelay?: number, SeparationRadius?: number, SeparationStrength?: number}
---@return Phoenix.Steering.SteeringComponent
function Phoenix.Steering.SteeringComponent.new(t) end

---@class Phoenix.Transform2D
---@field Position Phoenix.Vec2
---@field Rotation number
---@field Scale number
Phoenix.Transform2D = {}

---@param t? {Position?: Phoenix.Vec2, Rotation?: number, Scale?: number}
---@return Phoenix.Transform2D
function Phoenix.Transform2D.new(t) end

---@class Phoenix.Vec2
---@field X number
---@field Y number
Phoenix.Vec2 = {}

---@param t? {X?: number, Y?: number}
---@return Phoenix.Vec2
function Phoenix.Vec2.new(t) end

---@param a Phoenix.Vec2
---@param b Phoenix.Vec2
---@param threshold number
---@return boolean
function Phoenix.Vec2.Equals(a, b, threshold) end

---@param a Phoenix.Vec2
---@param b Phoenix.Vec2
---@return number
function Phoenix.Vec2.Distance(a, b) end

---@param s Phoenix.Vec2
---@param n Phoenix.Vec2
---@param p Phoenix.Vec2
---@return Phoenix.Vec2
function Phoenix.Vec2.Project(s, n, p) end

---@param normal Phoenix.Vec2
---@param vector Phoenix.Vec2
---@return Phoenix.Vec2
function Phoenix.Vec2.Reflect(normal, vector) end

---@param a Phoenix.Vec2
---@param b Phoenix.Vec2
---@return Phoenix.Vec2
function Phoenix.Vec2.Midpoint(a, b) end

---@param angle number
---@param radius number
---@return Phoenix.Vec2
function Phoenix.Vec2.FromPolar(angle, radius) end

---@class Phoenix.Unit : Phoenix.Entity
---@field _id integer
Phoenix.Unit = {}
---@return boolean
function Phoenix.Unit:IsAlive() end
---@param command Phoenix.RTS.Command
---@return boolean
function Phoenix.Unit:IssueCommand(command) end

---@param unitData integer|string
---@param owner integer
---@param pos Phoenix.Vec2
---@param facing number
---@param args integer
---@return integer
function Phoenix.Unit.SpawnUnit(unitData, owner, pos, facing, args) end

---@param unit integer
---@return integer
function Phoenix.Unit.GetOwner(unit) end

---@param unit integer
---@return integer|string
function Phoenix.Unit.GetUnitData(unit) end

---@class Phoenix.Entity
---@field _id integer
Phoenix.Entity = {}
---@return boolean
function Phoenix.Entity:IsValid() end
---@param tag integer|string
---@return boolean
function Phoenix.Entity:HasTag(tag) end
---@param tag integer|string
---@return boolean
function Phoenix.Entity:AddTag(tag) end
---@param tag integer|string
---@return boolean
function Phoenix.Entity:RemoveTag(tag) end
---@return Phoenix.Vec2
function Phoenix.Entity:GetPosition() end
---@return number
function Phoenix.Entity:GetFacing() end
---@param key integer|string
---@param defaultValue boolean
---@return boolean
function Phoenix.Entity:GetBlackboardValue_bool(key, defaultValue) end
---@param key integer|string
---@param defaultValue integer
---@return integer
function Phoenix.Entity:GetBlackboardValue_int(key, defaultValue) end
---@param key integer|string
---@param defaultValue integer
---@return integer
function Phoenix.Entity:GetBlackboardValue_unsigned_int(key, defaultValue) end
---@param key integer|string
---@param defaultValue integer
---@return integer
function Phoenix.Entity:GetBlackboardValue_int64(key, defaultValue) end
---@param key integer|string
---@param defaultValue integer
---@return integer
function Phoenix.Entity:GetBlackboardValue_uint64(key, defaultValue) end
---@param key integer|string
---@param defaultValue number
---@return number
function Phoenix.Entity:GetBlackboardValue_Value(key, defaultValue) end
---@param key integer|string
---@param defaultValue number
---@return number
function Phoenix.Entity:GetBlackboardValue_Angle(key, defaultValue) end
---@param key integer|string
---@param defaultValue number
---@return number
function Phoenix.Entity:GetBlackboardValue_Time(key, defaultValue) end
---@param key integer|string
---@param defaultValue number
---@return number
function Phoenix.Entity:GetBlackboardValue_Speed(key, defaultValue) end
---@param key integer|string
---@param defaultValue Phoenix.Vec2
---@return Phoenix.Vec2
function Phoenix.Entity:GetBlackboardValue_Vec2(key, defaultValue) end
---@param key integer|string
---@param defaultValue integer|string
---@return integer|string
function Phoenix.Entity:GetBlackboardValue_FName(key, defaultValue) end
---@param key integer|string
---@param defaultValue integer
---@return integer
function Phoenix.Entity:GetBlackboardValue_EntityId(key, defaultValue) end
---@param key integer|string
---@param defaultValue Phoenix.Color
---@return Phoenix.Color
function Phoenix.Entity:GetBlackboardValue_Color(key, defaultValue) end
---@param key integer|string
---@param value boolean
---@return boolean
function Phoenix.Entity:SetBlackboardValue_bool(key, value) end
---@param key integer|string
---@param value integer
---@return boolean
function Phoenix.Entity:SetBlackboardValue_int(key, value) end
---@param key integer|string
---@param value integer
---@return boolean
function Phoenix.Entity:SetBlackboardValue_unsigned_int(key, value) end
---@param key integer|string
---@param value integer
---@return boolean
function Phoenix.Entity:SetBlackboardValue_int64(key, value) end
---@param key integer|string
---@param value integer
---@return boolean
function Phoenix.Entity:SetBlackboardValue_uint64(key, value) end
---@param key integer|string
---@param value number
---@return boolean
function Phoenix.Entity:SetBlackboardValue_Value(key, value) end
---@param key integer|string
---@param value number
---@return boolean
function Phoenix.Entity:SetBlackboardValue_Angle(key, value) end
---@param key integer|string
---@param value number
---@return boolean
function Phoenix.Entity:SetBlackboardValue_Time(key, value) end
---@param key integer|string
---@param value number
---@return boolean
function Phoenix.Entity:SetBlackboardValue_Speed(key, value) end
---@param key integer|string
---@param value Phoenix.Vec2
---@return boolean
function Phoenix.Entity:SetBlackboardValue_Vec2(key, value) end
---@param key integer|string
---@param value integer|string
---@return boolean
function Phoenix.Entity:SetBlackboardValue_FName(key, value) end
---@param key integer|string
---@param value integer
---@return boolean
function Phoenix.Entity:SetBlackboardValue_EntityId(key, value) end
---@param key integer|string
---@param value Phoenix.Color
---@return boolean
function Phoenix.Entity:SetBlackboardValue_Color(key, value) end
---@param arg2 integer|string
---@return boolean|nil
function Phoenix.Entity:TryGetBlackboardValue_bool(arg2) end
---@param arg2 integer|string
---@return integer|nil
function Phoenix.Entity:TryGetBlackboardValue_int(arg2) end
---@param arg2 integer|string
---@return integer|nil
function Phoenix.Entity:TryGetBlackboardValue_unsigned_int(arg2) end
---@param arg2 integer|string
---@return integer|nil
function Phoenix.Entity:TryGetBlackboardValue_int64(arg2) end
---@param arg2 integer|string
---@return integer|nil
function Phoenix.Entity:TryGetBlackboardValue_uint64(arg2) end
---@param arg2 integer|string
---@return number|nil
function Phoenix.Entity:TryGetBlackboardValue_Value(arg2) end
---@param arg2 integer|string
---@return number|nil
function Phoenix.Entity:TryGetBlackboardValue_Angle(arg2) end
---@param arg2 integer|string
---@return number|nil
function Phoenix.Entity:TryGetBlackboardValue_Time(arg2) end
---@param arg2 integer|string
---@return number|nil
function Phoenix.Entity:TryGetBlackboardValue_Speed(arg2) end
---@param arg2 integer|string
---@return Phoenix.Vec2|nil
function Phoenix.Entity:TryGetBlackboardValue_Vec2(arg2) end
---@param arg2 integer|string
---@return integer|string|nil
function Phoenix.Entity:TryGetBlackboardValue_FName(arg2) end
---@param arg2 integer|string
---@return integer|nil
function Phoenix.Entity:TryGetBlackboardValue_EntityId(arg2) end
---@param arg2 integer|string
---@return Phoenix.Color|nil
function Phoenix.Entity:TryGetBlackboardValue_Color(arg2) end

-- Phoenix.Orders

---@param unit integer
---@param command Phoenix.RTS.Command
---@return boolean
function Phoenix.Orders.IssueCommand(unit, command) end

---@param unit integer
---@return boolean
function Phoenix.Orders.HasOrders(unit) end

-- Phoenix.RTS.AttackAbilityTask

---@return any
function Phoenix.RTS.AttackAbilityTask.GetTaskDefinition() end

-- Phoenix.RTS.MoveAbilityTask

---@return any
function Phoenix.RTS.MoveAbilityTask.GetTaskDefinition() end

-- Phoenix.RTS.ProjectileTask

---@return any
function Phoenix.RTS.ProjectileTask.GetTaskDefinition() end

-- Phoenix.RTS.VitalsTask

---@return any
function Phoenix.RTS.VitalsTask.GetTaskDefinition() end

-- Phoenix.Random

---@param seed integer
function Phoenix.Random.Seed(seed) end

---@return boolean
function Phoenix.Random.Next_bool() end

---@return integer
function Phoenix.Random.Next_int() end

---@return integer
function Phoenix.Random.Next_unsigned_int() end

---@return integer
function Phoenix.Random.Next_int64() end

---@return integer
function Phoenix.Random.Next_uint64() end

---@return number
function Phoenix.Random.Next_Value() end

---@return number
function Phoenix.Random.Next_Angle() end

---@return number
function Phoenix.Random.Next_Time() end

---@return number
function Phoenix.Random.Next_Speed() end

---@param min boolean
---@param max boolean
---@return boolean
function Phoenix.Random.Range_bool(min, max) end

---@param min integer
---@param max integer
---@return integer
function Phoenix.Random.Range_int(min, max) end

---@param min integer
---@param max integer
---@return integer
function Phoenix.Random.Range_unsigned_int(min, max) end

---@param min integer
---@param max integer
---@return integer
function Phoenix.Random.Range_int64(min, max) end

---@param min integer
---@param max integer
---@return integer
function Phoenix.Random.Range_uint64(min, max) end

---@param min number
---@param max number
---@return number
function Phoenix.Random.Range_Value(min, max) end

---@param min number
---@param max number
---@return number
function Phoenix.Random.Range_Angle(min, max) end

---@param min number
---@param max number
---@return number
function Phoenix.Random.Range_Time(min, max) end

---@param min number
---@param max number
---@return number
function Phoenix.Random.Range_Speed(min, max) end

---@param radius number
---@return Phoenix.Vec2
function Phoenix.Random.PointInCircle(radius) end

---@param radius number
---@return Phoenix.Vec2
function Phoenix.Random.PointOnCircle(radius) end

-- Phoenix.Steering

---@param entity integer
---@param target Phoenix.Vec2
---@param range number
---@return boolean
function Phoenix.Steering.MoveToLocation(entity, target, range) end

---@param entity integer
---@param target integer
---@param range number
---@return boolean
function Phoenix.Steering.FollowEntity(entity, target, range) end

---@param entity integer
---@return boolean
function Phoenix.Steering.IsMoving(entity) end

---@param entity integer
---@return boolean
function Phoenix.Steering.HasFinishedMoving(entity) end

---@param entity integer
---@param target integer
---@return boolean
function Phoenix.Steering.TurnToFaceEntity(entity, target) end

---@param entity integer
---@param target integer
---@return boolean
function Phoenix.Steering.TurnToFacePos(entity, target) end

---@param entity integer
---@return boolean
function Phoenix.Steering.IsTurning(entity) end

---@param entity integer
---@return boolean
function Phoenix.Steering.HasFinishedTurning(entity) end

---@param entity integer
---@return integer
function Phoenix.Steering.GetSteeringMode(entity) end

---@param entity integer
---@return boolean
function Phoenix.Steering.IsSeekingGoal(entity) end

---@param entity integer
---@return boolean
function Phoenix.Steering.HasArrivedAtGoal(entity) end

---@param entity integer
---@return boolean
function Phoenix.Steering.Stop(entity) end

---@param entity integer
---@return boolean
function Phoenix.Steering.IsHolding(entity) end

---@param entity integer
---@param holding boolean
---@return boolean
function Phoenix.Steering.SetHolding(entity, holding) end

---@param entity integer
---@param args any
---@return boolean
function Phoenix.Steering.UpdateSpeed(entity, args) end

---@param entity integer
---@return number
function Phoenix.Steering.GetInnerRadius(entity) end

---@param entity integer
---@return number
function Phoenix.Steering.GetOuterRadius(entity) end

-- Phoenix.Vitals

---@param target integer
---@param damage Phoenix.RTS.Damage
---@return boolean
function Phoenix.Vitals.ApplyDamage(target, damage) end

-- Phoenix.World

---@return integer|string
function Phoenix.World.GetId() end

---@return integer|string
function Phoenix.World.GetType() end

---@param key integer
---@return boolean
function Phoenix.World.HasBlackboardValue(key) end

---@param key integer
---@return boolean|nil
function Phoenix.World.TryGetBlackboardValue_bool(key) end

---@param key integer
---@return integer|nil
function Phoenix.World.TryGetBlackboardValue_int(key) end

---@param key integer
---@return integer|nil
function Phoenix.World.TryGetBlackboardValue_unsigned_int(key) end

---@param key integer
---@return integer|nil
function Phoenix.World.TryGetBlackboardValue_int64(key) end

---@param key integer
---@return integer|nil
function Phoenix.World.TryGetBlackboardValue_uint64(key) end

---@param key integer
---@return number|nil
function Phoenix.World.TryGetBlackboardValue_Value(key) end

---@param key integer
---@return number|nil
function Phoenix.World.TryGetBlackboardValue_Angle(key) end

---@param key integer
---@return number|nil
function Phoenix.World.TryGetBlackboardValue_Time(key) end

---@param key integer
---@return number|nil
function Phoenix.World.TryGetBlackboardValue_Speed(key) end

---@param key integer
---@return Phoenix.Vec2|nil
function Phoenix.World.TryGetBlackboardValue_Vec2(key) end

---@param key integer
---@return integer|string|nil
function Phoenix.World.TryGetBlackboardValue_FName(key) end

---@param key integer
---@return integer|nil
function Phoenix.World.TryGetBlackboardValue_EntityId(key) end

---@param key integer
---@return Phoenix.Color|nil
function Phoenix.World.TryGetBlackboardValue_Color(key) end

---@param key integer
---@param defaultValue boolean
---@return boolean
function Phoenix.World.GetBlackboardValue_bool(key, defaultValue) end

---@param key integer
---@param defaultValue integer
---@return integer
function Phoenix.World.GetBlackboardValue_int(key, defaultValue) end

---@param key integer
---@param defaultValue integer
---@return integer
function Phoenix.World.GetBlackboardValue_unsigned_int(key, defaultValue) end

---@param key integer
---@param defaultValue integer
---@return integer
function Phoenix.World.GetBlackboardValue_int64(key, defaultValue) end

---@param key integer
---@param defaultValue integer
---@return integer
function Phoenix.World.GetBlackboardValue_uint64(key, defaultValue) end

---@param key integer
---@param defaultValue number
---@return number
function Phoenix.World.GetBlackboardValue_Value(key, defaultValue) end

---@param key integer
---@param defaultValue number
---@return number
function Phoenix.World.GetBlackboardValue_Angle(key, defaultValue) end

---@param key integer
---@param defaultValue number
---@return number
function Phoenix.World.GetBlackboardValue_Time(key, defaultValue) end

---@param key integer
---@param defaultValue number
---@return number
function Phoenix.World.GetBlackboardValue_Speed(key, defaultValue) end

---@param key integer
---@param defaultValue Phoenix.Vec2
---@return Phoenix.Vec2
function Phoenix.World.GetBlackboardValue_Vec2(key, defaultValue) end

---@param key integer
---@param defaultValue integer|string
---@return integer|string
function Phoenix.World.GetBlackboardValue_FName(key, defaultValue) end

---@param key integer
---@param defaultValue integer
---@return integer
function Phoenix.World.GetBlackboardValue_EntityId(key, defaultValue) end

---@param key integer
---@param defaultValue Phoenix.Color
---@return Phoenix.Color
function Phoenix.World.GetBlackboardValue_Color(key, defaultValue) end

---@param key integer
---@param value boolean
---@return boolean
function Phoenix.World.SetBlackboardValue_bool(key, value) end

---@param key integer
---@param value integer
---@return boolean
function Phoenix.World.SetBlackboardValue_int(key, value) end

---@param key integer
---@param value integer
---@return boolean
function Phoenix.World.SetBlackboardValue_unsigned_int(key, value) end

---@param key integer
---@param value integer
---@return boolean
function Phoenix.World.SetBlackboardValue_int64(key, value) end

---@param key integer
---@param value integer
---@return boolean
function Phoenix.World.SetBlackboardValue_uint64(key, value) end

---@param key integer
---@param value number
---@return boolean
function Phoenix.World.SetBlackboardValue_Value(key, value) end

---@param key integer
---@param value number
---@return boolean
function Phoenix.World.SetBlackboardValue_Angle(key, value) end

---@param key integer
---@param value number
---@return boolean
function Phoenix.World.SetBlackboardValue_Time(key, value) end

---@param key integer
---@param value number
---@return boolean
function Phoenix.World.SetBlackboardValue_Speed(key, value) end

---@param key integer
---@param value Phoenix.Vec2
---@return boolean
function Phoenix.World.SetBlackboardValue_Vec2(key, value) end

---@param key integer
---@param value integer|string
---@return boolean
function Phoenix.World.SetBlackboardValue_FName(key, value) end

---@param key integer
---@param value integer
---@return boolean
function Phoenix.World.SetBlackboardValue_EntityId(key, value) end

---@param key integer
---@param value Phoenix.Color
---@return boolean
function Phoenix.World.SetBlackboardValue_Color(key, value) end

---@param s string
---@return integer
function Phoenix.Hash(s) end
