/*
 * lua_wasm.c — Lua 5.4 interpreter compiled to WASM for FeatureScript.
 *
 * This file provides the interpreter lifecycle and WASM export stubs.
 * All Phoenix host-function bridges and the Lua namespace table setup
 * live in lua_bridge.c, which is auto-generated by PhoenixWasmGen.
 *
 * Determinism:
 *   All Lua allocations go through WASM's malloc/realloc/free, which draw
 *   from WASM linear memory.  lua_State* is a 32-bit offset into that memory
 *   (not a native heap pointer), so the entire interpreter state is captured
 *   by a memcpy — enabling snapshot/restore rollback in WasmEnvironment
 *   without any extra bookkeeping.
 *
 * Memory:
 *   Compiled with -sALLOW_MEMORY_GROWTH=0 so linear memory size is fixed.
 *   WasmEnvironment's snapshot buffer must be >= INITIAL_MEMORY bytes.
 */

/* ── Lua 5.4 headers ──────────────────────────────────────────────────────── */
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"

#include <stdio.h>

/* ── Phoenix bridge (generated by PhoenixWasmGen) ────────────────────────── */
/*
 * lua_bridge.c provides:
 *   static void register_phoenix_api(lua_State* L);
 *
 * It is compiled as a separate translation unit alongside this file
 * (both are passed to emcc in the same invocation).
 */
void register_phoenix_api(lua_State* L);

/* ── Script buffer ────────────────────────────────────────────────────────── */
/*
 * The host writes Lua source bytes into g_script_buf, then calls LoadScript(len).
 * This avoids embedding the script at compile time and enables hot-reload.
 */
#define WASM_SCRIPT_BUF_SIZE (128 * 1024)

static char       g_script_buf[WASM_SCRIPT_BUF_SIZE];
static int        g_script_len = 0;
static lua_State* g_L          = NULL;

/* Returns the WASM-linear-memory address of the script buffer.
 * The host resolves this to a native pointer via m3_GetMemory. */
__attribute__((export_name("GetScriptBuffer")))
int GetScriptBuffer(void)
{
    return (int)(uintptr_t)g_script_buf;
}

/* Called by the host after writing script bytes into GetScriptBuffer().
 * Closes any live Lua state so the next lifecycle call re-initializes. */
__attribute__((export_name("LoadScript")))
int LoadScript(int len)
{
    if (len < 0 || len > WASM_SCRIPT_BUF_SIZE)
        return -1;
    if (g_L) { lua_close(g_L); g_L = NULL; }
    g_script_len = len;
    return 0;
}

/* ── Lua state ────────────────────────────────────────────────────────────── */

/*
 * Create (on first call) or return the Lua state for this world's WASM
 * linear memory.  Because each WasmEnvironment has its own wasm3 runtime
 * with independent linear memory, g_L is unique per world instance.
 */
static lua_State* ensure_state(void)
{
    if (g_L != NULL) return g_L;

    printf("[lua_wasm] luaL_newstate\n");
    g_L = luaL_newstate();
    if (!g_L) { printf("[lua_wasm] luaL_newstate failed\n"); return NULL; }

    printf("[lua_wasm] luaopen_base\n");
    luaL_requiref(g_L, "_G",             luaopen_base,   1); lua_pop(g_L, 1);
    printf("[lua_wasm] luaopen_math\n");
    luaL_requiref(g_L, LUA_MATHLIBNAME,  luaopen_math,   1); lua_pop(g_L, 1);
    printf("[lua_wasm] luaopen_string\n");
    luaL_requiref(g_L, LUA_STRLIBNAME,   luaopen_string, 1); lua_pop(g_L, 1);
    printf("[lua_wasm] luaopen_table\n");
    luaL_requiref(g_L, LUA_TABLIBNAME,   luaopen_table,  1); lua_pop(g_L, 1);

    printf("[lua_wasm] register_phoenix_api\n");
    register_phoenix_api(g_L);

    printf("[lua_wasm] luaL_loadbuffer\n");
    if (luaL_loadbuffer(g_L, g_script_buf, (size_t)g_script_len, "@script.lua") != LUA_OK)
    {
        printf("[lua_wasm] luaL_loadbuffer error: %s\n", lua_tostring(g_L, -1));
        lua_close(g_L);
        g_L = NULL;
        return NULL;
    }

    printf("[lua_wasm] lua_pcall (script body)\n");
    if (lua_pcall(g_L, 0, 0, 0) != LUA_OK)
    {
        printf("[lua_wasm] lua_pcall error: %s\n", lua_tostring(g_L, -1));
        lua_close(g_L);
        g_L = NULL;
        return NULL;
    }

    printf("[lua_wasm] ensure_state OK\n");
    return g_L;
}

/*
 * Call a no-arg global Lua function by name.
 * Silently skips missing globals so all callbacks are optional.
 */
static void call_void(lua_State* L, const char* name)
{
    lua_getglobal(L, name);
    if (!lua_isfunction(L, -1)) { lua_pop(L, 1); return; }
    if (lua_pcall(L, 0, 0, 0) != LUA_OK) { lua_pop(L, 1); }
}

/* ── GetLuaErrorMsg ───────────────────────────────────────────────────────── */
/*
 * Returns a WASM linear-memory pointer to a null-terminated string describing
 * the current Lua error (whatever is on top of the Lua stack).
 * Called by the host inside the _emscripten_throw_longjmp handler so the C++
 * side can log the actual Lua error message before the trap aborts execution.
 * Returns 0 if no Lua state exists or the stack is empty/non-string.
 */
static char g_lua_error_buf[512];

__attribute__((export_name("GetLuaErrorMsg")))
int GetLuaErrorMsg(void)
{
    if (!g_L) return 0;
    const char* msg = lua_tostring(g_L, -1);
    if (!msg) msg = "(no message on Lua stack)";
    int n = 0;
    while (msg[n] && n < (int)(sizeof(g_lua_error_buf) - 1)) { g_lua_error_buf[n] = msg[n]; n++; }
    g_lua_error_buf[n] = '\0';
    return (int)(uintptr_t)g_lua_error_buf;
}

/* ── WASM exports (called by WasmEnvironment::CallVoid) ──────────────────── */

__attribute__((export_name("OnWorldInitialize")))
void OnWorldInitialize(void)
{
    lua_State* L = ensure_state();
    if (L) call_void(L, "OnWorldInitialize");
}

__attribute__((export_name("OnWorldShutdown")))
void OnWorldShutdown(void)
{
    lua_State* L = ensure_state();
    if (L)
    {
        call_void(L, "OnWorldShutdown");
        lua_close(L);
        g_L = NULL;
    }
}

__attribute__((export_name("OnPreWorldUpdate")))
void OnPreWorldUpdate(void) { lua_State* L = ensure_state(); if (L) call_void(L, "OnPreWorldUpdate"); }

__attribute__((export_name("OnWorldUpdate")))
void OnWorldUpdate(void) { lua_State* L = ensure_state(); if (L) call_void(L, "OnWorldUpdate"); }

__attribute__((export_name("OnPostWorldUpdate")))
void OnPostWorldUpdate(void) { lua_State* L = ensure_state(); if (L) call_void(L, "OnPostWorldUpdate"); }

__attribute__((export_name("OnPreUpdate")))
void OnPreUpdate(void) { lua_State* L = ensure_state(); if (L) call_void(L, "OnPreUpdate"); }

__attribute__((export_name("OnUpdate")))
void OnUpdate(void) { lua_State* L = ensure_state(); if (L) call_void(L, "OnUpdate"); }

__attribute__((export_name("OnPostUpdate")))
void OnPostUpdate(void) { lua_State* L = ensure_state(); if (L) call_void(L, "OnPostUpdate"); }

/* ── RunString ────────────────────────────────────────────────────────────── */

/*
 * Execute a Lua snippet from the script buffer WITHOUT resetting the Lua
 * state.  Used by WasmEnvironment::RunString / FeatureLua::EnqueueScript.
 *
 * The host writes code bytes into GetScriptBuffer() then calls RunString(len).
 * The current global state (variables, functions) is preserved between calls.
 *
 * Returns 0 on success, negative on error.
 */
__attribute__((export_name("RunString")))
int RunString(int len)
{
    if (len < 0 || len > WASM_SCRIPT_BUF_SIZE) return -1;
    lua_State* L = ensure_state();
    if (!L) return -2;
    if (luaL_loadbuffer(L, g_script_buf, (size_t)len, "@<run_string>") != LUA_OK)
    {
        printf("[lua_wasm] RunString load error: %s\n", lua_tostring(L, -1));
        lua_pop(L, 1);
        return -3;
    }
    if (lua_pcall(L, 0, 0, 0) != LUA_OK)
    {
        printf("[lua_wasm] RunString pcall error: %s\n", lua_tostring(L, -1));
        lua_pop(L, 1);
        return -4;
    }
    return 0;
}
