---@meta
-- Auto-generated by PhoenixLuaGen — do not edit.
-- Provides LuaLS type annotations for the Phoenix host API.
-- Regenerate: build the PhoenixLuaGen target.

Phoenix = {}
Phoenix.FeatureDebug = {}
Phoenix.Orders = {}
Phoenix.Physics = {}
Phoenix.RTS = {}
Phoenix.Steering = {}
Phoenix.Vitals = {}

---@class Phoenix.Box2
---@field Min Phoenix.Vec2
---@field Max Phoenix.Vec2
Phoenix.Box2 = {}

---@param t? {Min?: Phoenix.Vec2, Max?: Phoenix.Vec2}
---@return Phoenix.Box2
function Phoenix.Box2.new(t) end

---@param a Phoenix.Vec2
---@param b Phoenix.Vec2
---@param c Phoenix.Vec2
---@return Phoenix.Box2
function Phoenix.Box2.FromPoints(a, b, c) end

---@class Phoenix.Circle2
---@field Origin Phoenix.Vec2
---@field Radius number
Phoenix.Circle2 = {}

---@param t? {Origin?: Phoenix.Vec2, Radius?: number}
---@return Phoenix.Circle2
function Phoenix.Circle2.new(t) end

---@class Phoenix.Color
---@field B integer
---@field R integer
---@field G integer
---@field A integer
Phoenix.Color = {}

---@param t? {B?: integer, R?: integer, G?: integer, A?: integer}
---@return Phoenix.Color
function Phoenix.Color.new(t) end

---@param arg0 integer
---@return Phoenix.Color
function Phoenix.Color.FromHex(arg0) end

---@class Phoenix.ECS
---@field bDebugDrawMortonCodeBoundaries boolean
---@field bDebugDrawEntityZCodes boolean
Phoenix.ECS = {}

---@param t? {bDebugDrawMortonCodeBoundaries?: boolean, bDebugDrawEntityZCodes?: boolean}
---@return Phoenix.ECS
function Phoenix.ECS.new(t) end

---@param entity integer
---@param tag integer|string
---@return boolean
function Phoenix.ECS.AddTag(entity, tag) end

---@param kind integer|string
---@return integer
function Phoenix.ECS.AcquireEntity(kind) end

---@param entity integer
---@return integer
function Phoenix.ECS.RemoveAllTags(entity) end

---@param group integer
---@param entity integer
---@return boolean
function Phoenix.ECS.AddEntityToGroup(group, entity) end

---@param entity integer
---@return boolean
function Phoenix.ECS.ReleaseEntity(entity) end

---@param entity integer
---@param kind integer|string
---@return boolean
function Phoenix.ECS.SetEntityKind(entity, kind) end

---@param entity integer
---@param tag integer|string
---@return boolean
function Phoenix.ECS.HasTag(entity, tag) end

---@param entity integer
---@param tag integer|string
---@return boolean
function Phoenix.ECS.RemoveTag(entity, tag) end

---@param group integer
---@param entity integer
---@return boolean
function Phoenix.ECS.GroupContainsEntity(group, entity) end

---@param group integer
---@param entity integer
---@return boolean
function Phoenix.ECS.RemoveEntityFromGroup(group, entity) end

---@param entity integer
---@param target integer
---@param range number
---@return boolean
function Phoenix.ECS.IsInRangeOfEntity(entity, target, range) end

---@param id integer
---@param key integer|string
---@param bool boolean
---@return boolean
function Phoenix.ECS.RemoveBlackboardValue(id, key, bool) end

---@param entity integer
---@return integer
function Phoenix.ECS.RemoveEntityFromAllGroups(entity) end

---@param group integer
---@return integer
function Phoenix.ECS.ClearGroup(group) end

---@param entity integer
---@param target Phoenix.Vec2
---@param threshold number
---@return boolean
function Phoenix.ECS.IsFacingPos(entity, target, threshold) end

---@param group integer
---@return integer
function Phoenix.ECS.GetGroupSize(group) end

---@param id integer
---@param key integer|string
---@param type integer
---@return boolean
function Phoenix.ECS.HasBlackboardValue(id, key, type) end

---@param id integer
---@param key integer|string
---@param type integer
---@return integer
function Phoenix.ECS.CreateBlackboardKey(id, key, type) end

---@param id integer
---@param key integer|string
---@param value number
---@return boolean
function Phoenix.ECS.SetBlackboardValue(id, key, value) end

---@param id integer
---@param key integer|string
---@param defaultValue number
---@return number
function Phoenix.ECS.GetBlackboardValue(id, key, defaultValue) end

---@param entity integer
---@return Phoenix.Vec2
function Phoenix.ECS.GetLocalPosition(entity) end

---@param entity integer
---@param target integer
---@param threshold number
---@return boolean
function Phoenix.ECS.IsFacingEntity(entity, target, threshold) end

---@param entity integer
---@return number
function Phoenix.ECS.GetLocalFacing(entity) end

---@param entity integer
---@param target Phoenix.Vec2
---@param range number
---@return boolean
function Phoenix.ECS.IsInRangeOfPos(entity, target, range) end

---@param entity integer
---@return number
function Phoenix.ECS.GetLocalScale(entity) end

---@param entity integer
---@return Phoenix.Vec2
function Phoenix.ECS.GetWorldPosition(entity) end

---@param entity integer
---@return number
function Phoenix.ECS.GetWorldFacing(entity) end

---@param entity integer
---@return number
function Phoenix.ECS.GetWorldScale(entity) end

---@param entity integer
---@return integer
function Phoenix.ECS.GetParent(entity) end

---@class Phoenix.ECS.TransformComponent
---@field ZCode integer
---@field AttachParent integer
---@field Transform Phoenix.Transform2D
Phoenix.ECS.TransformComponent = {}

---@param t? {ZCode?: integer, AttachParent?: integer, Transform?: Phoenix.Transform2D}
---@return Phoenix.ECS.TransformComponent
function Phoenix.ECS.TransformComponent.new(t) end

---@class Phoenix.Ellipse2
---@field Origin Phoenix.Vec2
---@field Radius Phoenix.Vec2
Phoenix.Ellipse2 = {}

---@param t? {Origin?: Phoenix.Vec2, Radius?: Phoenix.Vec2}
---@return Phoenix.Ellipse2
function Phoenix.Ellipse2.new(t) end

---@class Phoenix.Line2
---@field Start Phoenix.Vec2
---@field End Phoenix.Vec2
Phoenix.Line2 = {}

---@param t? {Start?: Phoenix.Vec2, End?: Phoenix.Vec2}
---@return Phoenix.Line2
function Phoenix.Line2.new(t) end

---@class Phoenix.Physics.BodyComponent
---@field Force Phoenix.Vec2
---@field Flags integer
---@field Radius number
---@field LinearVelocity Phoenix.Vec2
---@field CollisionMask integer
---@field Movement integer
---@field MaxLinearVelocity number
---@field LinearDamping number
---@field InvMass integer
---@field SleepTimer integer
---@field PreviousPos Phoenix.Vec2
Phoenix.Physics.BodyComponent = {}

---@param t? {Force?: Phoenix.Vec2, Flags?: integer, Radius?: number, LinearVelocity?: Phoenix.Vec2, CollisionMask?: integer, Movement?: integer, MaxLinearVelocity?: number, LinearDamping?: number, InvMass?: integer, SleepTimer?: integer, PreviousPos?: Phoenix.Vec2}
---@return Phoenix.Physics.BodyComponent
function Phoenix.Physics.BodyComponent.new(t) end

---@class Phoenix.Physics.PhysicsSystem
---@field NumIterations integer
---@field DebugDrawContacts boolean
---@field PenetrationThreshold number
---@field AllowSleep boolean
---@field NumSolverSteps integer
---@field PenetrationCorrection number
---@field NumSeparationSteps integer
Phoenix.Physics.PhysicsSystem = {}

---@param t? {NumIterations?: integer, DebugDrawContacts?: boolean, PenetrationThreshold?: number, AllowSleep?: boolean, NumSolverSteps?: integer, PenetrationCorrection?: number, NumSeparationSteps?: integer}
---@return Phoenix.Physics.PhysicsSystem
function Phoenix.Physics.PhysicsSystem.new(t) end

---@class Phoenix.RTS.Command
---@field Flags integer
---@field Sender integer
---@field TargetEntity integer
---@field Kind integer
---@field TargetLocation Phoenix.Vec2
---@field CommandId integer|string
---@field CommandIndex integer
Phoenix.RTS.Command = {}

---@param t? {Flags?: integer, Sender?: integer, TargetEntity?: integer, Kind?: integer, TargetLocation?: Phoenix.Vec2, CommandId?: integer|string, CommandIndex?: integer}
---@return Phoenix.RTS.Command
function Phoenix.RTS.Command.new(t) end

---@class Phoenix.RTS.Damage
---@field Amount number
---@field ArmorMultiplier number
---@field VitalId integer|string
---@field BaseAmount number
---@field SourceId integer
Phoenix.RTS.Damage = {}

---@param t? {Amount?: number, ArmorMultiplier?: number, VitalId?: integer|string, BaseAmount?: number, SourceId?: integer}
---@return Phoenix.RTS.Damage
function Phoenix.RTS.Damage.new(t) end

---@class Phoenix.RTS.EffectComponent
---@field Name integer|string
---@field TargetId integer
---@field SourceId integer
---@field TargetPos Phoenix.Vec2
---@field SourcePos Phoenix.Vec2
---@field RefCount integer
---@field ChannelingCount integer
Phoenix.RTS.EffectComponent = {}

---@param t? {Name?: integer|string, TargetId?: integer, SourceId?: integer, TargetPos?: Phoenix.Vec2, SourcePos?: Phoenix.Vec2, RefCount?: integer, ChannelingCount?: integer}
---@return Phoenix.RTS.EffectComponent
function Phoenix.RTS.EffectComponent.new(t) end

---@class Phoenix.RTS.UnitComponent
---@field OwningPlayer integer
---@field UnitData integer|string
Phoenix.RTS.UnitComponent = {}

---@param t? {OwningPlayer?: integer, UnitData?: integer|string}
---@return Phoenix.RTS.UnitComponent
function Phoenix.RTS.UnitComponent.new(t) end

---@class Phoenix.Steering.SteeringComponent
---@field PreviousPos Phoenix.Vec2
---@field Velocity Phoenix.Vec2
---@field Mode integer
---@field GoalPos Phoenix.Vec2
---@field Flags integer
---@field CollisionMask integer
---@field GoalEntity integer
---@field Slack number
---@field BestPos Phoenix.Vec2
---@field InnerRadius number
---@field OuterRadius number
---@field ArrivalRange number
---@field MaxSpeed number
---@field TurnRateIdle number
---@field TurnRateMoving number
---@field AccelerationTime number
---@field DecelerationTime number
---@field AvoidanceRadius number
---@field SeparationDelay number
---@field SeparationRadius number
---@field SeparationStrength number
Phoenix.Steering.SteeringComponent = {}

---@param t? {PreviousPos?: Phoenix.Vec2, Velocity?: Phoenix.Vec2, Mode?: integer, GoalPos?: Phoenix.Vec2, Flags?: integer, CollisionMask?: integer, GoalEntity?: integer, Slack?: number, BestPos?: Phoenix.Vec2, InnerRadius?: number, OuterRadius?: number, ArrivalRange?: number, MaxSpeed?: number, TurnRateIdle?: number, TurnRateMoving?: number, AccelerationTime?: number, DecelerationTime?: number, AvoidanceRadius?: number, SeparationDelay?: number, SeparationRadius?: number, SeparationStrength?: number}
---@return Phoenix.Steering.SteeringComponent
function Phoenix.Steering.SteeringComponent.new(t) end

---@class Phoenix.Steering.SteeringSystem
---@field AvoidanceRadiusScalar number
---@field MoveTowardsGoal boolean
---@field SlackIncreaseRateFast number
---@field DensityScalar number
---@field AvoidanceScalar number
---@field DensityRadiusScalar number
---@field SlackIncreaseRate number
---@field ArrivalThreshold number
---@field SlackRateDivisor number
---@field SlackRateDivisorSlow number
---@field MaxSlack number
Phoenix.Steering.SteeringSystem = {}

---@param t? {AvoidanceRadiusScalar?: number, MoveTowardsGoal?: boolean, SlackIncreaseRateFast?: number, DensityScalar?: number, AvoidanceScalar?: number, DensityRadiusScalar?: number, SlackIncreaseRate?: number, ArrivalThreshold?: number, SlackRateDivisor?: number, SlackRateDivisorSlow?: number, MaxSlack?: number}
---@return Phoenix.Steering.SteeringSystem
function Phoenix.Steering.SteeringSystem.new(t) end

---@class Phoenix.Transform2D
---@field Position Phoenix.Vec2
---@field Rotation number
---@field Scale number
Phoenix.Transform2D = {}

---@param t? {Position?: Phoenix.Vec2, Rotation?: number, Scale?: number}
---@return Phoenix.Transform2D
function Phoenix.Transform2D.new(t) end

---@class Phoenix.Vec2
---@field X number
---@field Y number
Phoenix.Vec2 = {}

---@param t? {X?: number, Y?: number}
---@return Phoenix.Vec2
function Phoenix.Vec2.new(t) end

---@param a Phoenix.Vec2
---@param b Phoenix.Vec2
---@param threshold number
---@return boolean
function Phoenix.Vec2.Equals(a, b, threshold) end

---@param a Phoenix.Vec2
---@param b Phoenix.Vec2
---@return number
function Phoenix.Vec2.Distance(a, b) end

---@param s Phoenix.Vec2
---@param n Phoenix.Vec2
---@param p Phoenix.Vec2
---@return Phoenix.Vec2
function Phoenix.Vec2.Project(s, n, p) end

---@param normal Phoenix.Vec2
---@param vector Phoenix.Vec2
---@return Phoenix.Vec2
function Phoenix.Vec2.Reflect(normal, vector) end

---@param a Phoenix.Vec2
---@param b Phoenix.Vec2
---@return Phoenix.Vec2
function Phoenix.Vec2.Midpoint(a, b) end

---@param angle number
---@param radius number
---@return Phoenix.Vec2
function Phoenix.Vec2.FromPolar(angle, radius) end

---@class Phoenix.Unit : Phoenix.Entity
---@field _id integer
Phoenix.Unit = {}
---@return boolean
function Phoenix.Unit:IsAlive() end
---@param command Phoenix.RTS.Command
---@return boolean
function Phoenix.Unit:IssueCommand(command) end

---@param unitData integer|string
---@param owner integer
---@param pos Phoenix.Vec2
---@param facing number
---@param args integer
---@return integer
function Phoenix.Unit.SpawnUnit(unitData, owner, pos, facing, args) end

---@param unit integer
---@return integer
function Phoenix.Unit.GetOwner(unit) end

---@param unit integer
---@return integer|string
function Phoenix.Unit.GetUnitData(unit) end

---@param unitData integer|string
---@param owner integer
---@param pos Phoenix.Vec2
---@param facing number
---@return integer
function Phoenix.Unit.Spawn(unitData, owner, pos, facing) end

---@class Phoenix.Entity
---@field _id integer
Phoenix.Entity = {}
---@return boolean
function Phoenix.Entity:IsValid() end
---@param tag integer|string
---@return boolean
function Phoenix.Entity:HasTag(tag) end
---@param tag integer|string
---@return boolean
function Phoenix.Entity:AddTag(tag) end
---@param tag integer|string
---@return boolean
function Phoenix.Entity:RemoveTag(tag) end
---@return Phoenix.Vec2
function Phoenix.Entity:GetPosition() end
---@return number
function Phoenix.Entity:GetFacing() end

-- Phoenix

---@return integer|string
function Phoenix.GetWorldId() end

---@return integer|string
function Phoenix.GetWorldType() end

---@param min integer
---@param max integer
---@return integer
function Phoenix.RandomRange(min, max) end

---@return number
function Phoenix.RandomFloat() end

-- Phoenix.FeatureDebug

---@param circle Phoenix.Circle2
---@param color Phoenix.Color
function Phoenix.FeatureDebug.DrawCircle(circle, color) end

---@param ellipse Phoenix.Ellipse2
---@param color Phoenix.Color
function Phoenix.FeatureDebug.DrawEllipse(ellipse, color) end

---@param line Phoenix.Line2
---@param color Phoenix.Color
function Phoenix.FeatureDebug.DrawLine(line, color) end

---@param start Phoenix.Vec2
---@param dir Phoenix.Vec2
---@param color Phoenix.Color
function Phoenix.FeatureDebug.DrawRay(start, dir, color) end

---@param box Phoenix.Box2
---@param color Phoenix.Color
function Phoenix.FeatureDebug.DrawBox(box, color) end

---@param index integer
---@return Phoenix.Color
function Phoenix.FeatureDebug.GetColor(index) end

-- Phoenix.Orders

---@param unit integer
---@param command Phoenix.RTS.Command
---@return boolean
function Phoenix.Orders.IssueCommand(unit, command) end

---@param unit integer
---@return boolean
function Phoenix.Orders.HasOrders(unit) end

-- Phoenix.Vitals

---@param target integer
---@param damage Phoenix.RTS.Damage
---@return boolean
function Phoenix.Vitals.ApplyDamage(target, damage) end

---@param s string
---@return integer
function Phoenix.Hash(s) end
