name: Build (Emscripten)

on:
  pull_request:
    branches: [main]
  workflow_call:
    inputs:
      upload_artifact:
        required: false
        default: false
        type: boolean
      artifact_name:
        required: false
        default: PhoenixSim-wasm
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up EMSDK
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.18

      - name: Cache vcpkg binary packages
        uses: actions/cache@v4
        with:
          path: .vcpkg-binary-cache
          key: vcpkg-wasm-${{ hashFiles('vcpkg.json') }}
          restore-keys: vcpkg-wasm-

      - name: Create vcpkg binary cache dir
        run: mkdir -p .vcpkg-binary-cache

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        env:
          VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/.vcpkg-binary-cache

      - name: Set up sccache
        uses: mozilla-actions/sccache-action@v0.0.6

      - name: Cache sccache store
        uses: actions/cache@v4
        with:
          path: .sccache
          key: sccache-wasm-${{ github.run_id }}
          restore-keys: sccache-wasm-

      - name: Configure
        run: cmake --preset emscripten "-DCMAKE_CXX_COMPILER_LAUNCHER=$SCCACHE_PATH" "-DCMAKE_C_COMPILER_LAUNCHER=$SCCACHE_PATH"
        env:
          SCCACHE_GHA_ENABLED: "false"
          SCCACHE_DIR: ${{ github.workspace }}/.sccache

      - name: Build
        run: cmake --build --preset EmscriptenRelease
        env:
          SCCACHE_GHA_ENABLED: "false"
          SCCACHE_DIR: ${{ github.workspace }}/.sccache

      - name: Install
        if: inputs.upload_artifact
        run: |
          cmake --install .build/wasm --config Release --prefix .artifact
          cp README.md    .artifact/ 2>/dev/null || true
          cp CHANGELOG.md .artifact/ 2>/dev/null || true
          cp -r docs      .artifact/

      - name: Upload artifact
        if: inputs.upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: .artifact/
          if-no-files-found: error
