name: Build

permissions:
  contents: read
  packages: read
  actions: write

on:
  workflow_call:
    inputs:
      preset:
        required: false
        default: ci
        type: string
      config:
        required: false
        default: ReleaseCI
        type: string
      generate_artifact:
        required: false
        default: false
        type: boolean
      artifact_dir:
        required: false
        default: .artifact
        type: string
 
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [ReleaseCI]
    steps:

      - name: Install build dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y autoconf autoconf-archive automake libtool
          sudo apt-get update && sudo apt-get install -y ninja-build

      - uses: actions/checkout@v4
        with:
          submodules: true # Ensure vcpkg directory is actually populated

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        env:
          # 'clear' removes defaults, 'nuget' points to the source we just added
          VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"
      
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Configure CMake
        run: cmake --preset ${{ inputs.preset }}

      - name: Build CMake targets
        run: cmake --build --preset ${{ inputs.config }}

      # TODO: figure out how to determine the buildDir by the configurePreset. For now assume it's always .build_ci.
      - name: Install
        run: cmake --install "$GITHUB_WORKSPACE/.build_ci/" --config ${{ inputs.config }} --prefix "$GITHUB_WORKSPACE/${{ inputs.artifact_dir }}"

      - name: Bundle Artifact
        if: inputs.generate_artifact == true
        run: |
          artifactDir="$GITHUB_WORKSPACE/${{ inputs.artifact_dir }}"
          docsDir="$GITHUB_WORKSPACE/docs"
          cp LICENSE "$artifactDir" || true
          cp README.md "$artifactDir" || true
          cp CHANGELOG.md "$artifactDir" || true
          cp -r "$docsDir" "$artifactDir" || true

      - name: List Artifact Files
        run: find "$GITHUB_WORKSPACE/${{ inputs.artifact_dir }}" -type f

      - name: Upload artifact
        if: inputs.generate_artifact == true
        uses: actions/upload-artifact@v4
        with:
          name: PhoenixSim-${{ github.sha }}.zip
          path: ${{ github.workspace }}/${{ inputs.artifact_dir }}/**
          if-no-files-found: error
