name: CI

permissions:
  contents: read
  packages: read
  actions: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      generate_artifact: false
    secrets: inherit