name: Release

permissions:
  contents: read
  packages: read
  actions: write

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      generate_artifact: true
    secrets: inherit

  attach-artifact:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: PhoenixSim-${{ github.sha }}.zip
      - name: Rename artifact
        shell: pwsh
        run: Rename-Item -Path 'PhoenixSim-${{ github.sha }}.zip' -NewName 'PhoenixSim-${{ github.ref_name }}.zip'
      - name: Attach artifact to release
        uses: softprops/action-gh-release@v1
        with:
          files: PhoenixSim-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
